export const COMMANDS = {
  price: '!price',
  shortPrice: '!p',
  weight: '!weight',
  shortWeight: '!w',
  rep: '!factionrep',
  shortRep: '!rep',
  rarity: '!rarity',
  shortRarity: '!r',
  value: '!value',
  shortValue: '!v',
  wiki: '!wiki',
  tracker: '!tracker',
  map: '!map',
  loadout: '!loadout',
  geo: '!geo',
  calc: '!calc',
  progress: '!progress',
  questAmount: '!qamount',
  upgradeAmount: '!uamount',
  craftAmount: '!camount',
  forgeAmount: '!famount',
  info: '!info'
}